version: '0.1'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Porta do frontend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Porta do backend
