# Use uma imagem base com Node.js
FROM node:18

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o arquivo package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Compile o código TypeScript para JavaScript
RUN npm run build

# Exponha a porta na qual o app será executado
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "start"]
